### ISSUE TITLE
Can we use our definition(s) to categorize current features that are "on the edge"?

### ISSUE THREAD

**Issue by atopal** [web-platform-dx/web-features#240] opened 2023-06-22 14:51 UTC
Can we use our definition(s) to categorize current features that are "on the edge"? And use that to guide our decision making?

This was one of the issues we prioritized during our workshop on Baseline on June 16.

**Comment by jdatapple** [comment] 2023-06-22 17:01
This is an excellent approach to understanding if a given definition of Baseline results in feature categorization that fits or mostly fits with expectations. I'd go further to suggest creating several models for a subset of features "on the edge" with different Baselines definitions in order to get insights on best fit definitions, and perhaps glean better insights into why a given definition may be a better fit or not.

**Comment by dfabulich** [comment] 2023-06-22 19:37
Here's a CSV of caniuse feature IDs, market share, and "keystone" release date (the date of the release of the last major browser to support the feature).

[caniuse-marketshare-dates.csv](https://github.com/web-platform-dx/feature-set/files/11839547/caniuse-marketshare-dates.csv)

We're using the very latest version of caniuse's data for this, not any historical data, and so we're not impacted by https://github.com/Fyrd/caniuse/issues/6733 for the purposes of this analysis.

When sorting by market share, and filtering for features between 94 and 95% market share, these features emerge:

feature_id|marketshare|keystone_date
---|---|---
css-revert-value|94.02|2020-07-16
webgl2|94.02|2021-09-20
mediarecorder|94.7|2021-04-26
webp|94.77|2022-09-12
css-gradients|94.82|2022-03-14
bigint|94.85|2020-09-16
element-scroll-methods|94.89|2021-04-26
prefers-color-scheme|94.98|2020-01-15

Here's a list of other models I could imagine generating:

1. Raw StatCounter: caniuse preprocesses StatCounter's data, but we've found a bug in that before, and there might be more. We could try to download the latest StatCounter data and reproduce the data ourselves. (Hopefully this would just generate the same results as above.)
2. RUM Archive: We could attempt to compute market share using RUM archive's data. Since they don't list minor Safari versions, we'd have to make some assumptions, e.g. that all Safari 16 users are on 16.0, or that all Safari 16 users are on the latest Safari 16.4
3. CloudFlare Radar: CloudFlare Radar _currently_ has no browser version share data publicly available at all, but I'm optimistic that we'll be able to get access to that data at some point.

We've also discussed defining Baseline based on months since the date of the release of the last major browser to support the feature (the "keystone" release date). But we haven't really reached consensus on what number of months to consider. You can sort the CSV by keystone_date and eyeball it to find plausible edge cases yourself.

For your amusement, here's a table of a handful of features slightly more than two years old.

feature_id|marketshare|keystone_date
---|---|---
css-image-orientation|93.66|2021-03-04
flexbox-gap|92.87|2021-04-26
mediarecorder|94.7|2021-04-26
element-scroll-methods|94.89|2021-04-26
audio-api|96.56|2021-04-26
css-sticky|93.78|2021-05-27

And here's a handful of features around three years old.

feature_id|marketshare|keystone_date
---|---|---
resizeobserver|95.14|2020-03-24
input-event|97.3|2020-03-24
css-math-functions|93.82|2020-04-08
css-read-only-write|96.52|2020-06-30
css-revert-value|94.02|2020-07-16

**Comment by ddbeck** [comment] 2024-09-16 11:28
This is one of several issues around developing the Baseline definition, from last year. While this discussion was fruitful for formulating the definition, I don't think there are any active plans to survey developers along these lines. Since this is a bit historic now, I'm going to close this issue. If I've missed something, however, please file a new issue or request to reopen this one with more details. Thank you!

**Closed by ddbeck** 2024-09-16 11:28 UTC
Labels: baseline definition
