### ISSUE TITLE
compute-baseline: empty support object when feature in pre release?

### ISSUE THREAD

**Issue by Elchi3** [web-platform-dx/web-features#1275] opened 2024-06-24 12:06 UTC
I'm using the new `computeBaseline` function to calculate baseline based on single BCD keys. 

I wonder if it excludes support data for features in pre releases on purpose? (Might also be that I'm doing something wrong.)

I'm doing this with a fresh BCD:

```js
import { computeBaseline } from "compute-baseline";

console.log(
JSON.parse(computeBaseline({compatKeys: ["api.Blob.bytes"], withAncestors: false}).toJSON())
);
```

It returns:

```js
{ baseline: false, support: {} }
```

I would have expected:

```js
{ baseline: false, support: { firefox: '128'} }
```

**Comment by ddbeck** [comment] 2024-06-24 12:16
This is a duplicate of https://github.com/web-platform-dx/web-features/issues/955. It's something I'd like to fix, I just haven't found the time yet.

The short summary is that this is intentional, until we can change the schema to show consumers that a future release supports a feature without disrupting the overall status calculation.

**Closed by ddbeck** 2024-06-24 12:16 UTC

**Comment by Elchi3** [comment] 2024-06-24 13:13
Thank you Daniel! I will wait for #955 then. 
By chance, do you have any pointers in the code where I could change this to include pre releases for testing?

**Comment by ddbeck** [comment] 2024-06-24 13:39
https://github.com/ddbeck/web-features/blob/34b8ac9ec5037c4a0d06a0f3f450861c1a7a4144/packages/compute-baseline/src/baseline/support.ts#L27-L32

I think if you replace this with `support.set(b, lastInitialRelease(unqualifiedReleases));` alone (that is, it always happens, unconditionally, no if-else), you'll get close to the result you're looking for.
